# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    container_name: nestjs_api
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    command: sh -c "npx prisma migrate dev --name auto_migration && yarn start:dev"
    depends_on:
      db:
       condition: service_healthy
   
  db:
    image: postgres
    restart: always
    container_name: nestjs_postgres
    volumes:
      - db-data:/var/lib/postgresql 
    env_file:
      - .env
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d nest_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

